<<: &shared
  language_name: SENĆOŦEN
mappings:
  - display_name: SENĆOŦEN equivalency
    mapping: str_equiv.json
    in_lang: str
    out_lang: str-equiv
    rule_ordering: as-written
    norm_form: NFD
    case_sensitive: true
    authors:
      - Shankhalika Srikanth
    <<: *shared
  - display_name: SENĆOŦEN to IPA
    mapping: str_to_ipa.json
    in_lang: str-equiv
    out_lang: str-ipa
    rule_ordering: as-written
    norm_form: NFD
    case_sensitive: true
    authors:
      - Aidan Pine
    <<: *shared
nodes:
  str:
    normalized_inventory:
      - A
      - Á
      - Ⱥ
      - B
      - C
      - Ć
      - Ȼ
      - D
      - E
      - H
      - I
      - Í
      - J
      - K
      - ₭
      - K\u0301
      - K\u0331
      - L
      - Ƚ
      - M
      - "N"
      - N\u0331
      - O
      - P
      - Q
      - S
      - Ś
      - T
      - Ⱦ
      - Ṯ
      - Ŧ
      - U
      - W
      - W\u0331
      - X\u0331
      - "Y"
      - Z
      - "s"
      - "¸"




