<<: &shared
  language_name: Gitksan
mappings:
  - display_name: Orthography
    in_lang: git
    out_lang: git-ipa
    rule_ordering: as-written
    case_sensitive: false
    authors:
      - Fineen Davis
    mapping: git_to_ipa.json
    <<: *shared
  - display_name: Rigsby APA
    in_lang: git
    out_lang: git-apa
    authors:
      - Fineen Davis
    mapping: RAPA_Deterministic.csv
    <<: *shared
  - display_name: Unicode Equivalencies
    in_lang: git
    out_lang: git-equiv
    authors:
      - Aidan Pine
    mapping: equiv.csv
    <<: *shared
  - display_name: Gitksan IPA to English IPA
    in_lang: git-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    authors:
      - Aidan Pine
    mapping: git_ipa_to_eng_ipa.json
    <<: *shared
nodes:
  git:
    normalized_inventory:
      - a
      - aa
      - b
      - d
      - e
      - ee
      - g
      - gw
      - g\u0332
      - h
      - hl
      - i
      - ii
      - j
      - k
      - k'
      - kw
      - kw'
      - k\u0332
      - k\u0332'
      - l
      - "'l"
      - m
      - "'m"
      - "n"
      - "'n"
      - o
      - oo
      - p
      - p'
      - s
      - t
      - t'
      - tl'
      - ts
      - ts'
      - u
      - uu
      - w
      - "'w"
      - x
      - xw
      - x\u0332
      - "y"
      - "'y"
      - "'"