<<: &shared
  language_name: Kwak'wala
mappings:
  - display_name: Kwak'wala (NAPA) to IPA
    rules_path: kwk_napa_to_ipa.csv
    in_lang: kwk-napa
    out_lang: kwk-ipa
    rule_ordering: apply-longest-first
    case_sensitive: false
    norm_form: 'NFD'
    authors:
      - Patrick Littell
      - Fineen Davis
    language_name: Kwak'wala (NAPA orthography)
  - display_name: Kwak'wala (U'mista) to IPA
    rules_path: kwk_umista_to_ipa.json
    in_lang: kwk-umista-equiv
    out_lang: kwk-ipa
    rule_ordering: apply-longest-first
    case_sensitive: false
    prevent_feeding: true
    norm_form: 'NFD'
    authors:
      - Patrick Littell
      - Eric Joanis
    <<: *shared
  - display_name: Kwak'wala (U'mista) Equivalencies
    rules_path: umista_equiv.csv
    in_lang: kwk-umista
    out_lang: kwk-umista-equiv
    rule_ordering: apply-longest-first
    case_sensitive: false
    preserve_case: true
    prevent_feeding: true
    norm_form: 'NFD'
    authors:
      - Fineen Davis
      - Eric Joanis
    language_name: Kwak'wala (U'mista orthography)
  - display_name: Kwak'wala (NAPA) Equivalencies
    rules_path: napa_equiv_ubc.csv
    in_lang: kwk-napa-ubc
    out_lang: kwk-napa-ubc-equiv
    rule_ordering: apply-longest-first
    case_sensitive: false
    preserve_case: true
    norm_form: 'NFD'
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (NAPA) Equivalencies
    rules_path: napa_equiv_uvic.csv
    in_lang: kwk-napa-uvic
    out_lang: kwk-napa-uvic-equiv
    rule_ordering: apply-longest-first
    case_sensitive: false
    preserve_case: true
    norm_form: 'NFD'
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (Boas) to Umista
    rules_path: kwk_boas_to_umista.csv
    in_lang: kwk-boas
    out_lang: kwk-umista
    rule_ordering: apply-longest-first
    prevent_feeding: true
    case_sensitive: false
    preserve_case: true
    norm_form: 'NFD'
    authors:
      - Fineen Davis
      - Olivia Chen
      - Daisy Rosenblum
      - Dante cerron
    language_name: Kwak'wala (Boas orthography)
